name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_number:
          - 1

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install npm dependencies
        run: npm install # switch to `npm ci` when Node.js 6 support is dropped

      - name: Run tests
        commands:
          - "export COVERALLS_SERVICE_NAME=${{COVERALLS_SERVICE_NAME}}"
          - "export COVERALLS_GIT_BRANCH=${{CF_BRANCH}}"
          - "export COVERALLS_REPO_TOKEN=${{COVERALLS_REPO_TOKEN}}"
          - "npm install --save-dev jest"
          - "npm run test" 
          
        run: npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: MgHy694j47dEguq5evFM7GNbJ90sm3xgq0yGf
          flag-name: ${{matrix.os}}-node-${{ matrix.node }}
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: MgHy694j47dEguq5evFM7GNbJ90sm3xgq0yGf
          parallel-finished: true